### ISSUE TITLE
Server Certificate is not trusted installing the Trusted Agent

### ISSUE THREAD

**Issue by jemm14** [opencit/opencit#4]
Greetings,

I have the following problem when I try to install the Trusted agent:

`Warning: All server certificates were rejected; check MTWILSON_TLS_CERT_SHA1 
Error: Error from DownloadMtWilsonTlsCertificate: Validation failed 
Warning: Validating DownloadMtWilsonTlsCertificate: Keystore does not contain any Mt Wilson TLS certificates 
Error: Error while executing setup: Encountered errors during setup 
Register TPM password with service to support asset tag automation? [y/n] [no] y
Username: [admin] admin
Password: [********] ********
Error: Setup task error: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Server certificate is not trusted 
Error: Cannot run RegisterTpmPassword: Setup error 
Error: Error while executing setup: Encountered errors during setup`

I did already what the guide said (enviroment variable MTWILSON_TLS_CERT_SHA1 with /etc/inte/cloudsecurity/ssl.crt) but the problem persists.

Besides that  I get  everywhere in the mtwilson portal:

> java.security.cert.CertificateException: Server certificate is not trusted

and I cannot do anything like add a host or view a certificate , etc , cause I get the same error (catalina.out):

`Rejecting untrusted server certificate; repository already has 2 trusted certificates
javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Server certificate is not trusted
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1884)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1341)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:153)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:804)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
.....
` 

Do I have to get the server certificate signed by a CA? or there is a way to avoid that (I am using the software with educational purposes so everything is under localhost (127.0.0.1) installed)

Could you guys give me a hand with it. I would appreciate it

Thanks in advance.

**Comment by ZahediAquino** [comment]
@jemm14, Please try the following:

1) Run tagent uninstall (to clean up previous installation)
2) Reboot your server and in BIOS clear TPM
3) Reboot and reactivate TPM/TXT in the BIOS
4) Reboot to your OS again.
5) Also please go to this url on your browser: https://YOURSERVERIPGOESHERE:8443/mtwilson/v2/util/trustagent-env-file.html 
Note: Change YOURSERVERIPGOESHERE with your Servers actual IP

And compare the value of:
MTWILSON_TLS_CERT_SHA1=eeb9d481bd779b9a6dfcf65a5ee9b2f889906e02 

with what’s in your trustagent.env file? They should match
6) Run the tagent installer again.

If this fails, please send us the full catalina.out log file (from server) and install.log file from host (/opt/trustagent/logs/).

**Comment by jemm14** [comment]
@ZahediAquino,

thank you for your quick answer.

I could  solve the problem with the trustagent-env-file.html file , but now I have the following:

`5615 [main] ERROR c.i.m.s.console.cmd.SetupManager - Error from RequestEndorsementCertificate: Validation failed
5617 [main] WARN  c.i.m.s.console.cmd.SetupManager - Validating RequestEndorsementCertificate: Unable to verify TPM EC with 15 authorities from /opt/trustagent/configuration/endorsement.pem.EC is also not registered with Mt.Wilson
5619 [main] ERROR com.intel.dcsg.cpg.console.Main - Error while executing setup: Encountered errors during setup`

I tried again after installation:

> tagent setup

and:

> tagent authorize

but I get the same error.
I also tried in mtwilson:

> mtwilson setup SetupManager create-privacy-ca --no-exec
> mtwilson setup SetupManager create-endorsement-ca --no-exec

but apparently they dont work, I get:

> Unrecognized command

in /opt/mtwilson/configuration there are EndorsementCA.pem and EndorsementCA.p12 and
in /opt/tagent/configuration there is also a endorsement.pem

what do you think is the problem?

(besides that I still have the problem "java.security.cert.CertificateException: Server certificate is not trusted" in mtwilson portal)

Greetings.

**Comment by ciclismolibre** [comment]
Did you get to solve this issue?
I'm having the same problem :(

**Comment by jemm14** [comment]
yeah, that was cause i was using newer installations with older database
installations. I cleared the database, installed again and that problem
was fixed 

Am 2016-09-14 15:47, schrieb ciclismolibre: 

> Did you get to solve this issue?
> I'm having the same problem :( 
> 
> ## 
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

## Links:

[1] https://github.com/opencit/opencit/issues/4#issuecomment-247017924
[2]

**Comment by 19LukaModric** [comment]
Hi, I met the same problem. I deleted the database 'mw_as' of postgresql on opencit server, and executed the following command to erase users and data on server. Lastly I reinstalled the server and the trust agent. But when i reinstalled the trust agent, I still met the problem. 
Did I miss any key point or do something wrong? Any advice and help will be appreciated!

**Comment by 19LukaModric** [comment]
Hi, I met the same problem. I deleted the database 'mw_as' of postgresql on opencit server, and executed the following command to erase users and data on server.
    mtwilson zeroize
    mtwilson erase-data
    mtwilson erase-users --all
Lastly I reinstalled the server and the trust agent. But when i reinstalled the trust agent, I still met the problem. 
Did I miss any key point or do something wrong? Any advice and help will be appreciated!

**Comment by ZahediAquino** [comment]
Did you try 'mtwilson uninstall'  after mtwilson eras-users --all? Then Reinstalling the server?

**Comment by 19LukaModric** [comment]
Yes. I also did the 'tagent uninstall --purge' for the trust agent, then separately used .bin files to reinstalling the server and the trust agent.But the problem still exist.

747 ERROR [main] c.i.m.setup.console.cmd.Setup - Error from RequestEndorsementCertificate: Validation failed
748 WARN  [main] c.i.m.setup.console.cmd.Setup - Validating RequestEndorsementCertificate: [com.intel.mtwilson.setup.faults.ValidationFault: Unable to verify TPM EC with 15 authorities from /opt/trustagent/configuration/endorsement.pem.EC is also not registered with Mt.Wilson]
751 ERROR [main] c.i.m.launcher.console.Dispatcher - Error while executing setup: Encountered errors during setup
